### ISSUE TITLE
CryptoEcon Review

### ISSUE THREAD

**Issue by irenegia** [protocol/retriev#1]
The MVP was designed with a system of incentive and we asked to the CryptoEcon team at PL to review this system and help understanding the correct values for the parameters used there (see documentation [here](https://www.notion.so/pl-strflt/Data-Retrievability-Oracle-252f52f47b3944e8a54e8d0f553c5cd7#2023f5f015ef44719922402706e2ba95)).

Request made here 
https://github.com/protocol/CryptoEconLab-private/issues/68

Tag @alejandroterrazas

**Comment by irenegia** [comment]
Update: last week we got the first round of recommendations!

**Comment by irenegia** [comment]
**Notes from 18th May call.**

- We went over the hackMD and clarified all comments/questions there;
- We brainstormed about the reputation score mechanism #2;
- We discussed next steps and timeline. In particular, we agree on two action items:
  - (1) The current model does not use the variable m_d (the deposit margin) so, no recommendations for this. We want to enhance the model (or create an orthogonal model) to analisy the variable m_d
  - (2) Design the reputation score mechanism.

We think (2) is more time sensitive than (1) because it could involve changing the smart contract code (while (2) will only cause a change in the parameters).

Todo:

- [ ] @irenegia check with devs and set a clear timeline and due date for (1) and (2)

**Comment by irenegia** [comment]
Hey @danlessa and @alejandroterrazas,
about the timeline: we would need to have the crytpoecon review done by July 22nd.
Do you think it is feasible?

Also, should we set a call for this week?

**Comment by danlessa** [comment]
@irenegia I believe so

**Comment by danlessa** [comment]
@irenegia on the m_s being defined by the client and having an maximum value:

It won't affect most of the analysis, but it provides the case for recommending an even bigger value of m_s: 1000 rather than 100. 

Having a large allowable m_s while being tunable have some interesting consequences, like having an bargaining process that involves the payment (the provider reward) and m_s (related to how much collateral + risk the provider should accept). This can provide a lot of data for further developments

**Comment by irenegia** [comment]
**Update**

In the current version of the protocol: the provider has a balance in its account (internal to the smart contract), the balance decrees  at every accepted deal (ie, provider has balance b in the account and he accepts a deal with collateral c, then the balance is b- c).

> Note tokens are moved internally and temporarily blocked, it's not a gas-expensive operation. Tokens are not moved from contract to user, just in an internal balance. When the provider (or any other party) wants to move the tokens at that time they're actually transferred from contract to user, emptying the internal balance. This also means that the provider can withdraw from its “available” balance, which will be made of the eventual payments it received and the balance not blocked in deals


Given this, we all agreed that do not require the parameter m_d anymore!

**Comment by irenegia** [comment]
The research work here is done, the outcome is: 

- remove the deposit margin parameter $m_d$
- recommended value for the slashing multiplier $m_s$ is 1000
- recommended number for the committee multiplier is 0.2 (
- recommended max for the number of appeals if 5

The `collateral` and `payment` are chosen by the client but the smart contract checks that
- `collateral` $\leq$ available balance
- `payment` $\leq$ `collateral` $\leq m_s $ * `payment`

Once @turinglabsorg confirms these values and checks are in the code, we can close the issue! Thanks!

CC @danlessa

**Comment by turinglabsorg** [comment]
@irenegia let's take 1h to review together the code and verify everything is as expected, we can include this topic in our next call on Tuesday @0xjona

**Comment by 0xjona** [comment]
I’ll set this in the AGENDA expected on Monday

**Comment by irenegia** [comment]
>@irenegia let's take 1h to review together the code and verify everything is as expected, we can include this topic in our next call on Tuesday @0xjona

good idea, I'll paper a check list with all the stuff we need to check

**Comment by 0xjona** [comment]
we are validating the outputs of the research this week

**Comment by 0xjona** [comment]
@irenegia can we close this issue?

**Comment by irenegia** [comment]
yes, work done, documentation will be included in th paper #39
