### ISSUE TITLE
CLI improvements

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#11]
Command Line Softwares for Providers and Referees

**Comment by 0xjona** [comment]
do we still need this?

**Comment by turinglabsorg** [comment]
yes we need this but it's not needed for 1st release

**Comment by 0xjona** [comment]
@turinglabsorg do we still need this?

**Comment by turinglabsorg** [comment]
@0xjona it was a generic issue, now we moved in something more specific so i would say no
