### ISSUE TITLE
Move to PL servers all the servers to make load tests

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#13]

**Comment by irenegia** [comment]
- [ ] @irenegia will resume communication with the PL ops team
- [ ] @turinglabsorg move the servers

**Comment by turinglabsorg** [comment]
@irenegia one question, we registered `pldr.dev` for development purpose (we need the SSL so at least one domain), now we're changed the name to `retriev` should we buy something like `retriev.dev` or we can continue with previous domain?

**Comment by irenegia** [comment]
Up to you, for me kepping `pldr.dev` is fine.
The product name many change again before launch...

**Comment by turinglabsorg** [comment]
Ok! Let's change just one time once we define the product name!

Servers are moved, i'm waiting for DNS update and the ports from PL ops team. In the meanwhile the pre-alpha is offline, don't know if it's better to communicate it in Slack.

**Comment by irenegia** [comment]
Yes sure, let's send a message in the private channel!

However in the future, I would like to use the public channel
#retrivability-oracle t for this kind of updates.


@0xjona we first need to send a first official message to start using it, let's sync about this ASAP!

**Comment by turinglabsorg** [comment]
Alpha is back online and network was successfully migrated to PL server!
