### ISSUE TITLE
Create an API to support fast sync of current blockchain state, needed for a smooth UX

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#14]

**Comment by 0xjona** [comment]
is this expected for first release?

**Comment by turinglabsorg** [comment]
yes

**Comment by turinglabsorg** [comment]
Api deployed here: `https://api.pldr.dev`.

Active endpoint it's something like this: https://api.pldr.dev/deals/0xBE2F1803Cd7c886cD53778ADEF56d6AF7F8f9bD9
