### ISSUE TITLE
Reputation score mechanism

### ISSUE THREAD

**Issue by irenegia** [protocol/retriev#2]
We want to design a reputation score mechanism for the providers that we can use during testnet in order to 
1) incentivize early adoption of the protocol;
2) de-risk users to lose money.

cc @lucaniz, @nicola

**Comment by irenegia** [comment]
18th May: started to brainstorm some possible features with @danlessa

1. it would be good if the score goes up over time;
2. proportional to the deal duration: a deal valid for a months counts more (gives higher score) than a deal valid for 1 day;
3. no dependency on the payment variable (?);

**Comment by lucaniz** [comment]
After further brainstorm with @irenegia, a possible mitigation for Idea2 could be to allow only "old" clients (for instance, clients on FIlecoin/Etheruem for 1+ years) to distribute points to providers. 

This will prevent the creation of new siblings inflating malicious providers' reputation. 

Nevertheless, the "old" siblings can influence reputation mechanism.

**Comment by nicola** [comment]
I see two strategies, maybe they are similar to what you have in mind:

1. Go FIL+ style: there are some nodes that give out points to users and users spend these points with providers
2. No tokens at all: a miner wants to build a track record of successful deals, no tokens involved (premium price is 0)

**Comment by irenegia** [comment]
Yes, strategy number 1 is the one we are discussing more.
A first attempt to build that is :

- Each client can request a fixed budget of points if it meets some criteria that can prove the client identity is authentic. For example, the client was created at least 1 year ago; 
  - To be decided here: who checks the credential? Who release the coin? Smart contract or centralised? 
 - Each time a client does a proposal, there is a function that from the proposal parameters (eg, duration, payment, collateral) compute the point value of the proposal (ie, an amount of points attached with the proposal); 
- The provider that accepts this proposal and does not get slashed will get this points (which are also removed from the client budget);
  - To be decided here: we require that the provider is not slashed or that no appeal is made?!

**Comment by nicola** [comment]
cc: @anorth @kubuxu

**Comment by irenegia** [comment]
@turinglabsorg 's proposal:
- no reputation points, leave the protocol as it is (deposit, collateral, etc) and just create an ad-hoc token ERC-20 ("wrapped FIL"). Collateral, deposit, fees and slashing will be done with this token.
  - Pros: no extra line of code in the contract, also we test the actual protocol.
  - Cons: it works an economic incentive only if we can "promise" now some future conversion in FIL

**Comment by danlessa** [comment]
FYI: I've been brainstorming properties and desirables at https://hackmd.io/8CSLDfKNSAyyl-OfEzOdDQ

**Comment by 0xjona** [comment]
Working with ERC-20 tokens will nonetheless require us sometime (estimates @turinglabsorg ?) to work on the smartcontract, which is now coded to work with ETH!
We need to turn the **open questions** as a checklist to be defined by a due date

**Comment by turinglabsorg** [comment]
i think it will take 5-6 working days to fix everything and make tests, but we need to be 100% sure, because it requires the same time if we need to re-invent a token system..

**Comment by 0xjona** [comment]
So it’s 5-6 working days to implement the ERC-20 (or same time to design something like a custom tailored score system).
- What if we use ERC-20 but just as a form of payment/premium from client to provider?
It means freezing all the other variables
- otherwise, where does the provider gets the token from? And how much? 

We can make the tokens not transferable apart from _faucet —> client —> smartcontract (vaulted in deals) —> provider (that can’t do anything with them)_ ; so that at the end we just count the tokens and release a ranking!

**Comment by irenegia** [comment]
**Update**

We agreed on:
- we NOT going to create any ERC 20 token, payment and collateral are going to be in the native token of the blockchain used
- the reputation score is going to be an independent mechanism (independent of the smart contract code)
- the reputation mechanism is going to be a mechanism that looks at the events on chain, collect all the data about deals for a provider and then transform the data in a score (number in a scale)
   - @danlessa and I started to brainstorm the formula to transform deal data in a score [here](https://hackmd.io/8CSLDfKNSAyyl-OfEzOdDQ?both)

**Comment by 0xjona** [comment]
This is great!
We need to start breaking down this issue and turn the concept work into an upgrade of how we expect our website to work (if this “leaderboad/query toolkit” is going to be available there)

**Comment by irenegia** [comment]
I forgot to update this last week, my bad.
Anyway, we discussed about the formula, notes are here https://hackmd.io/8CSLDfKNSAyyl-OfEzOdDQ#14jun22

**Comment by turinglabsorg** [comment]
> [devs] design how we query the blockchain to get the data (@turinglabsorg ?)

Queries are done by the API so we can cache them and fast-readable, once we agree on the mechanism i will add it on the api!

**Comment by 0xjona** [comment]
work will happen in #58
