### ISSUE TITLE
Client website

### ISSUE THREAD

**Issue by irenegia** [protocol/retriev#25]
The client website https://pldr.dev/ misses some features. For example:

- [x] How does the client appeal? Proposal: add an appeal button

- [x] Each field needs some explanations and max/min values stated explicetely

**Comment by turinglabsorg** [comment]
>  How does the client appeal? Proposal: add an appeal button

you can actually appeal, there's a button that shows right under the card (if an appeal can be created, this means if deal is not expired or if there's no another appeal for same hash). Of course UX/UI will be improved.

**Comment by irenegia** [comment]
I don't see it :(
[image: Screenshot 2022-05-24 at 10.02.20.jpg]

-----------------------------------
*Irene Giacomelli*
Researcher at Protocol Labs
LinkedIn <https://www.linkedin.com/in/igiacomelli/> / Website
<https://irenegiacomelli.weebly.com>

**Comment by turinglabsorg** [comment]
Will repost a previous video later today where's showed the button, pretty sure is it here :-)

**Comment by turinglabsorg** [comment]
Closing because all issues was solved with the latest release
