### ISSUE TITLE
Naming [product design step 0]

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#26]
We’re having a serie of issues related to the design of the visual identity and UX of the alpha.

**_Step 0_** is a brainstorming session hold by @irenegia and @nicola to come up with narrative/metaphor to communicate the product and identify each part/moment of the protocol!
This will help us set the limits and directions for the next stage of design.

@claudiofabbro will join this process to better learn about the protocol itself.

**Comment by 0xjona** [comment]
@nicola @irenegia the call is set 
Naming brainstorming
Tuesday 5.31  11:20–12:20
Link https://meet.google.com/xti-pegc-pks

We can switch to zoom if you prefer
Please come prepared to optimise the time we have

**Comment by 0xjona** [comment]
Tomorrow we’ll close the process about “naming”, it is not a due date yet but it means that the team won’t work actively on this and we’ll be waiting for a round of feedbacks while working on the visual identity of the protocol! Today is last day to improve the brainstorming
https://filecoinproject.slack.com/archives/C03CJKWP2DR/p1654073649082749

**Comment by irenegia** [comment]
@nicola

**Comment by irenegia** [comment]
in yesterday presentation i decided to keep using the old name "retrievability consortium" and use the analogy with sport for explaining the referee role

**Comment by 0xjona** [comment]
### UPDATES
https://filecoinproject.slack.com/archives/C03CJKWP2DR/p1655202577854459

**Comment by 0xjona** [comment]
#### POLL RESULTS
![Image](https://user-images.githubusercontent.com/103100279/174391208-5a0a4dcf-d3a0-4125-8b1a-1cdf60c0243c.png)

**Comment by 0xjona** [comment]
we've choosen _Retrieval-pinning_ for now, considering this protocol as part of composable protocols
