### ISSUE TITLE
Key visuals [product design step 1]

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#27]
In step 1 we are designing the key visuals.
- First we’ll have a 2 propositions draft of the visual identity, moving toward one detailed brand identity
- Then we’ll develop the _iconographic setting_ and the related diagrams and use cases of it

@claudiofabbro will help us define the deliverables and the process
We’ll have a round of reviews to be scheduled

EPIC #34

**Comment by claudiofabbro** [comment]
**step 1 – Key visuals**

**Research phase (week 22-23)**
- [ ] Collect informations on FileCoin visual identity @claudiofabbro  
- [ ] Collect references on competitors / similar players in the field @claudiofabbro 
- [ ] Publish a document for the research phase / results of the analysis (optional) @claudiofabbro @0xjona  

— NAMING / STEP 0 NEEDS TO BE FINISHED HERE —
 
**Design phase (week 24)**
- [ ] Sketch (at least) 2 proposals for the logotype @claudiofabbro 
- [ ] Set up the color palette @claudiofabbro 
- [ ] Select the fonts and define a typographic palette @claudiofabbro 

**Approval phase (week 25)**
- [ ] Share the proposals and collect feedbacks @claudiofabbro @0xjona 
- [ ] Fine tuning on the proposals @claudiofabbro  

**Optional**
- [ ] Design a "how-to-use" visual identity guide @claudiofabbro

**Comment by 0xjona** [comment]
@claudiofabbro questions for tomorrow briefing @irenegia 
- how much should filecoin and/or protocol labs identities (plus related works at https://protocol.ai/work) influence DataRetriev one? (E.g. the hexagon symbol)
- do we have any official guideline to respect? 
- What do you expect from this visual identity? (E.g. does it have to refer any specific imaginary or we have _Carte blanche_ ?)

This comments also apply for #28 
The more we know from the client, the quickest we can be! 
Otherwise it takes a bit more to envision and design

**Comment by irenegia** [comment]
> how much should filecoin and/or protocol labs identities (plus related works at https://protocol.ai/work) influence DataRetriev one? (E.g. the hexagon symbol)

we are not bounded by the PL identity, use it if it helps!


> do we have any official guideline to respect?

I don't think so

> What do you expect from this visual identity? (E.g. does it have to refer any specific imaginary or we have Carte blanche ?)

it would be go to have something that recall web3 and cloud storage, if possible

**Comment by 0xjona** [comment]
presentation to be held on Tuesday 6.21
