### ISSUE TITLE
Homepage design [product design step 2]

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#28]
In step 2 we are designing together with @claudiofabbro the UX of the alpha version of the product and the landing page.

Coming after a few weeks of work from now, when we’ll have defined all the components of the ALPHA and what the landing page is about.

We’ll have to collect all the inputs coming from key references (e.g. https://drand.love )

**Comment by claudiofabbro** [comment]
**step 2 – Alpha UX and home page**

**Research phase (week 23-24)**
- [ ] Collect references on competitors / similar players in the field @claudiofabbro 
- [ ] Publish a document for the research phase / results of the analysis (optional) @claudiofabbro @0xjona  

— KEY VISUALS / STEP 1 NEEDS TO BE IN AN ADVANCED STAGE HERE —
 
**Design phase (week 25)**
- [ ] Sketch 1 proposal for the homepage @claudiofabbro 
- [ ] Set up a direct line with the web coder @claudiofabbro @0xjona 

**Approval phase (week 26)**
- [ ] Share the proposals and collect feedbacks @claudiofabbro @0xjona 
- [ ] Fine tuning on the proposals @claudiofabbro

**Comment by 0xjona** [comment]
briefing here is also about #copy

**Comment by 0xjona** [comment]
https://web3.storage/ 
https://nft.storage/

**Comment by 0xjona** [comment]
@irenegia here’s a checklist of what the homepage will be about
- [ ] Link to lite paper (update this with relative documentation issue)
- [ ] link GitHub with readme (updated with Install guide)
- [ ] link to news (this could either be https://mirror.xyz or https://medium.com so it’s external for now
- [ ] short about (explaining mainly the “metaphor” used)
- [ ] team section (how many people are involved? So that we start imaging the relative _space_ needed
- [ ] link to launch the MVP/ALPHA (which will open a new tab, with an intro/disclaimer before connecting wallet)

@claudiofabbro @Steve-Rog 

Do we have other references?
https://protocol.ai/work

**Comment by 0xjona** [comment]
@irene how do you expect the **team** section?

Exact questions are:
- How many people? 
- name surname, and max 4 word for description is ok?
- no pictures, right?

**Comment by irenegia** [comment]
> name surname, and max 4 word for description is ok?
no pictures, right?


Yep!

bumb of persons = us, the team 
 this! :)

**Comment by 0xjona** [comment]
The team is
- [ ] @irenegia 
- [ ] @nicola
- [ ] @lucaniz
- [ ] @Turinglabs
- [ ] @Steve-Rog 
- [ ] @claudiofabbro 
- [ ] @0xjona 

?

**Comment by 0xjona** [comment]
**UPDATE FROM WEEKLY CHECK-IN** for @claudiofabbro 
We should consider to add
- [ ] contributors to add in the team section 

we expect this to be on bottom line with a _sequence_ of names

- [ ] link slack channel to add

we expect this to be slack (+ eventually twitter) logo on the footer bottom right below "news/teams" section

**Comment by nicola** [comment]
Let's avoid the team page on the website, the spirit is that this is a very simple lightweight composible protocol, not a company/product. We should keep it as lightweight as possible. It's ok to have team page on discord or on github.

**Comment by irenegia** [comment]
> Let's avoid the team page on the website, the spirit is that this is a very simple lightweight composible protocol, not a company/product. We should keep it as lightweight as possible. It's ok to have team page on discord or on github.

ok

**Comment by irenegia** [comment]
> The team section is in the footer so it’s not so visible; we can redesign it to look more like an acknowledgment page (plus some notes about cryptonet as a whole) rather than a corporate team page! @claudiofabbro

discussed with Nicola, we only need a "contributors" section

**Comment by claudiofabbro** [comment]
> 

No problem, I'll fix it
