### ISSUE TITLE
Client UX - ALPHA

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#29]
Working on the design of UI/UX of the **client side** of the ALPHA

**Comment by 0xjona** [comment]
belongs to 2nd release / alpha protocol design has to be ready

**Comment by irenegia** [comment]
@0xjona do we have a label for the 2nd release, or a way to filter the issues that belongs to it.

**Comment by 0xjona** [comment]
WIP

**Comment by 0xjona** [comment]
### comments about UX improvements in call with @claudiofabbro @Steve-Rog @irenegia 
- Welcome (intro page with preview before accessing with metamask)
- Disclaimer
- Menus
- Notifications
- Remove client-side withdraw
- Status filter (colours)
- CTA create/manage (+ log)
- "Info" are non-requisite suggestions to be able to send the deal
- Duration (units of measurement, etc.)
- Providers box (all visible, disappear if the characteristics of the proposed deal are different from the policies set by the providers / I can choose multiple providers)
- Opensea link (file previews?) [API if they don't work as I know?]

**Comment by 0xjona** [comment]
**Via CLI**
- Price policy
- IPFS size check
- Accept
- [remote pinning key]

**Provider UI dApp**
- Entry with key 
- Online stats (+ scanning network)
- Score - active deals - withdraw (how much earned)

**Comment by 0xjona** [comment]
See #64 for upgrades to UI

**Comment by 0xjona** [comment]
Check our draft https://www.figma.com/proto/Mn96jGh4T4giJDa1eUb5uC/Retrieval-Pinning-%2F-dApp?page-id=0%3A1&node-id=201%3A124&viewport=-422%2C527%2C0.28&scaling=min-zoom&starting-point-node-id=201%3A124

**Comment by 0xjona** [comment]
### open questions

- We thought about the possibility of giving a custom name per each deal, after the “create deal phase”, only in the dashboard page; it’s an off chain name that can be edited (we designed it so that clients won’t confuse this editing with editing anything inside the deal, in fact the name si not a field while creating the deal); deals are automatically named e.g. “Deal n1” ecc but can be renamed to better go through them (imagine having 100 deals) [explored in the current UI proposition]
- What happens if I create a new deal on the same file? Do we need a special create deal on the same file once the deal expires? 
- We will change “appeal requested” to appear in orange, and add “slashed” to appear in red for deals slashed (consequently adding a new field in the status filter)
- We thought about a small preview of the file (but if it’s a folder or anything else there’s no preview) that could maybe help understand immediately if the file is correct (but we can’t add the preview in the create deal section cause the file might not me online yet, right?)
- How is price calculated? We designed it to mainly reference the duration, since then we will multiply it to the price per kilobyte set by the provider. 
- So we’ll have recommended prices dealing both with the settings from the provider to automatically accept deals, but also to the protocol concept (so if you can set a lower collateral, a disclaimer will pop up)
- We imagine you can only pick one provider for now; how is this actually working? What is exactly the expert mode?
- About duration, which unit of measurements should we use? 
- Can the disclaimer be present only at the beginning?
- Is ok to have the gas price on top?

**Comment by 0xjona** [comment]
### comments after call with @irenegia  and @turinglabsorg 

- we should keep the disclaimer inside the dapp untile we go mainnet
- “Gas price” must be turned into “internal deposit and network”
- Maybe “create deal” should stay on top rather than below
- Link tue homepage somewhere, maybe in the footer? Let’s make a better use of it
- “Blu part” could be shorter; it means let’s use it for useful information and let’s go straight to the usable part below 
- Yes add slashed filter but also “cancelled” (maybe in blue?), these are the deals the user cancelled before being accepted
- Names shouldn’t be editable for now, interesting idea but can’t be implemented now
- Search bar for deal URI to quickly find a specific deal
- Refresh button must be for each single deal
- “Choose deal duration”, means we should use verbs to indicate action 
- We should clear the “deal creation page” to make it as basic and usable for novel users vs more complicated for users being experts of our protocols: it means a simple Interface should have the “deal uri” and “appeal addres” uneditable, and a secondary position in respect to “upload image”; then the clients should be able to choose one provider only and the duration, after that prices will result and appear automatically  (@irenegia still editable in basic mode?); in expert mode everything is editable (and alerts will pop up)
