### ISSUE TITLE
/install readme “how-to-run” the demo

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#38]
On GitHub we need to provide users with an /install guide 
_reference https://github.com/drand/drand#installation_

What do we expect for 1st release?
- [ ] ?

**Comment by turinglabsorg** [comment]
I'll write the first draft of the documentation, topics will be:
- How to install a Provider node
- How to install a Referee node
- How to build from source both packages

**Comment by turinglabsorg** [comment]
Closing as it ready and published at https://github.com/protocol/retriev/blob/main/README.md
