### ISSUE TITLE
LITEPAPER

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#39]
@irenegia will covert notion documentation into a LITEPAPER

What program will you use?
What do we expect to have for #35 ?

**Comment by irenegia** [comment]
We will use Overleaf ([link](https://www.overleaf.com/read/fpskbrpjjjmh)).

I think that for the 28th oj june we can have the paper written down in review phase.
do you agree @lucaniz?

**Comment by lucaniz** [comment]
Yes!

**Comment by irenegia** [comment]
At the end, i decided to use HackMD
https://hackmd.io/@irenegia/BkqNihVY5

**Comment by 0xjona** [comment]
@irenegia can we link it? @Steve-Rog

**Comment by irenegia** [comment]
yep, sure!
Some sections are still WIP, but I can just mark those, np!
