### ISSUE TITLE
Cryptonet protocol review

### ISSUE THREAD

**Issue by irenegia** [protocol/retriev#42]
@anorth
The protocol design is described in this notion for now.
https://www.notion.so/pl-strflt/Retrievability-Insurance-Protocol-638e218831904eb18e5dc4d7db505c60

Let us know here or there is you have questions/comments!

**Comment by anorth** [comment]
I made a bunch of comments, thanks. There are a few things that seem more complicated than necessary to me (one regarding deposit ratio parameter that had already come up in Slack).

Also it's not clear to me if the provider will still get paid if they successfully serve the file to the referee.

Finally, one item that is overlooked is how often a client can force the provider to provide the file via the committee, without any additional payment to the provider. Just once? Infinitely many times? Is the assurance for unlimited retrieval or just once?

**Comment by irenegia** [comment]
> Also it's not clear to me if the provider will still get paid if they successfully serve the file to the referee.

no, no payment for the provider if there was an appeal (even one terminated with no slash)

> It is an outcome of #1 that we need to bound the max number of appeals per deal (proposed bound is 5)

**Comment by turinglabsorg** [comment]
@irenegia can we close this issue?

**Comment by turinglabsorg** [comment]
As discussed with @irenegia and @lucaniz we're closing as completed.
