### ISSUE TITLE
Front-end improvements "MVP --> ALPHA"

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#43]
We are improving the experience of using the MVP with details coherent with recent discussions and feedbacks, so that everyone can wrap their head around what’s happening via the protocol!

This constant update is carried by @Steve-Rog and in the coming weeks will follow up the design process #29 from @claudiofabbro

**Comment by Steve-Rog** [comment]
- Improvements Navbar functions
- Added link to dApp
- Added button "Signup as Provider"
- Added UI page for "Signup"
- Added OpeSea link for deals
- Updated Notification functions 
- Updated new contract on UI
- Added Modal disclaimer for the input "Provider Endpoint"

**Comment by Steve-Rog** [comment]
- Favicon updated
- "news" link removed
- Button text changed to "Launch App".
- Fix home page - footer overlapping with button (If we knew the viewport where this happens it would be better for a "definitive" fix)
- Increased text spacing on about page and separated paragraphs for readability

**Comment by Steve-Rog** [comment]
**Client UI**

Notification:
- Added notification when transaction is ended (create deal)
- Added notification when Provider can't accept a deal proposal

Messages:
- Messages and notifications are received only by the deal owner

Others:
- Disabled input fields on "create deal proposal" when dApp is working
