### ISSUE TITLE
OOO

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#47]
If we want to track when we are Out-Of-Office we can use this issue and regularly update it, so that we can plan accordingly all together!

I’m aware this will be a public information, we can think about another way if you prefer.
Nonetheless, we need to coordinate so that release dates or other important milestones don’t overlap with our OOO time.

**Comment by 0xjona** [comment]
@turinglabsorg in august will be travelling but available; doesn’t know yet the days off
@Steve-Rog from the 6th to the end of august will be OOO
@irenegia will leave on the 25th of July (so 22nd last day)

**Comment by turinglabsorg** [comment]
Closing this issue since is not part of tech tracking.
