### ISSUE TITLE
Key rotation and appeal key for random checks to prevent self deals

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#59]

**Comment by turinglabsorg** [comment]
This should be changed in:
- Appeal key for client: client can choose it's address or another address (smart contract or regular address) to make deals
- "Admin" appeal key: an key owned by the protocol enabled to run random checks to prevent self deals

Do you agree @irenegia @nicola @0xjona?

**Comment by irenegia** [comment]
I agree, closing this issue and opening two new ones, see #65 and #66
