### ISSUE TITLE
"Appeal key"

### ISSUE THREAD

**Issue by irenegia** [protocol/retriev#65]
We want to allow others to be able to create appeal for a deal created by the client X.

We decided that we can implement this by modifying the "create proposal" function.
In the new version the client can specify another address (different form the default that is the client address) that can send an on-chain message to create an appeal.

**Comment by 0xjona** [comment]
The appeal key is one, the client sets it while creating the deal. 
It is your own address by default, and it can be changed in #64 to be the address of for example a smart contract that includes multiple addresses aka appeal keys

**Comment by 0xjona** [comment]
A variation to this would be having an admin key see #66, which doesn’t affect the idea of the appeal key

**Comment by turinglabsorg** [comment]
@0xjona for me it's an appeal address, addresses are hashed version of keys. They're comparable but not exactly the same. In any case it's an address allowed to make transactions.

**Comment by nicola** [comment]
Ok to call it a appeal address.

The appeal addresses should be a list of keys and it should contain all keys that the client picks at deal creation. We don't have to force the deal creator key to be in the appeal address. Imagine preparers that resell this product to other people which do not want to include themselves.

**Comment by turinglabsorg** [comment]
So it's a list? In our first iteration we said it should be just one address, it's pretty the same for me, just need to understand if it's an array of addresses or a single address. We must be sure there's at least one appeal address or not?

**Comment by turinglabsorg** [comment]
ok, @nicola, created as list inside the contract and made tests to be sure everything works at protocol level. @0xjona we can close it.

**Comment by irenegia** [comment]
(hackMD updated)
