### ISSUE TITLE
Provider software upgrades CLI

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#67]
Working on the CLI for the provider.

**Via CLI**
- Price policy
- IPFS size check
- Auto-accept
- [remote pinning key]

**Comment by irenegia** [comment]
More details:

We discussed about a provider software that via command line will:
- Set up a node on a remote server (always on-line)
- Sign up to the protocol
- Create a **deal policy** that specify the minimum value accepted as payment (per byte and per unit of times)
- For each deal proposal received, will check if the params there satisfy the policy.  If yes, the proposal is automaticlaly accepted. 

cc @turinglabsorg to be sure I am right! :)

**Comment by turinglabsorg** [comment]
@irenegia we calculated a "suggested" price policy for the provider?

There's something we can add as default values? The formula should be something like:

```
min_price = value * duration * size
```

right?

Working on this document to make some tests: https://docs.google.com/spreadsheets/d/1zd8hVlL2GA1hTBJoeWm5LXnZLlcesDxdFWH1eB1afs0/edit#gid=0

**Comment by irenegia** [comment]
I understood this in a different way:

- the provider has its own policy where `value`
- in the app, when a client create a proposal we suggest as `payment` the value : `min_price = value * duration * size`

**Comment by turinglabsorg** [comment]
Yes of course, it's like you said, I'm just investigating if we can add some default values to provider software to be sure and in the meantime I was trying to understand real use cases.

Provider will add some minimum price for each second of pinning and then the dapp will show this price and will adjust total value accordingly to provider's policy.

Here I'm discussing if we need some default value when the provider runs the node for the first time (10 Wei for example) then the provider will be able to change it of course!

**Comment by irenegia** [comment]
Ah yes, got it!

We can see how much is to storing on other networks and propose something similar (eg, filecoin price).
Or the price of some centralised solution (AWS)?

Or, third option: we can set the default to zero! (like providers are doing this at the beginning for free to test their software/hardware and get reputation and then will ask for a price)

**Comment by turinglabsorg** [comment]
> Or, third option: we can set the default to zero! (like providers are doing this at the beginning for free to test their software/hardware and get reputation and then will ask for a price)

@irenegia as you proposed default value is `0` :fire:

**Comment by irenegia** [comment]
update about the provider's policy

 - Each provider has a *deal policy* that states:
        -  the `min_price`:  minimum price per second per byte, 
        -  the `max_rate`:  maximum rate (collateral/payment) 
        - the `max_size`: maximum file size accepted in a proposal  
    - The default values are `min_price`= 0,  `max_rate` = `slashing_multiplier` (here `slashing_multiplier` is a protocol parameter, see "protocol parameters" section), and `max_size`= 20MB.

**Comment by turinglabsorg** [comment]
@irenegia we should mention also provider can now add also the `max_collateral_multiplier` to avoid deals too risky, since hackmd is also updated i think we can now close this issue!

**Comment by turinglabsorg** [comment]
@irenegia we should mention also provider can now add also the `max_collateral_multiplier` to avoid deals too risky, since hackmd is also updated i think we can now close this issue!
