### ISSUE TITLE
Doing the Work-Breakdown-structure to define a grid of activities and the consequent GANTT chart.

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#8]

**Comment by 0xjona** [comment]
GITHUB-UPDATE
A review and an update from the first week of building a GitHub project.

inbox;  backlog;  breakdown;  todo;  implementation;  validation;  done
 inbox are the issues that do not yet have reference design docs and have not started a process of brainstorming and definition, it is also an icebox as those are issues that we are not sure we will implement, when and how.  These is the issues status as soon as they are created
 backlog are the issues we are discussing, which we have decided to implement but which are not yet in the todo list as they are not priority or not satisfactorily defined (it is not a todo list)
 breakdown | triage are the issues that need, before entering the todo-list, to be simplified into more specific issues (and this does not mean that they need clarification, otherwise they should be found in the backlog or inbox with a needs/clarification label);  it could also be the issues that are blocked (status stuck)
 todo is the list of issues ready to be carried out, with the priority assigned, etc.
 implementation means "we are writing the code” or ”we are actually producing this content"
 validation means that we have entered the definitive review / validation process
 done when they were closed (and then there could be a time distinction)


other fields
 active |  stuck |  done —> we can review this field as it should be a field inside the column and managed by the assignee: it means that every time the issue is moved from one column to another it undergoes a process (the breakdown process if necessary, or the implementation or validation etc), this process can be active, stuck for some reason (and here you can move back to triage to undergo a further breakdown or brainstorming process if necessary) or done (and you need done rules, i.e. that the breakdown is finished if for example a design doc has been produced).
 priority (0 urgent, 3 non-urgent)
due dates (to be made explicit only when referring to external consultancy or necessary deadlines external to the milestones)
 and the labels

About labels

dif/ —> easy, medium, hard, expert, trivial 
outsourced; content-request; dependencies; help wanted 
kind/ —> enhancement; discussion; support; maintenance; suggestion; BUG; test; monitor; review 
topic/ —> documentation; infrastructure , design-front-end; design-ux; product-design; protocol-research; PM 
effort/ —> hours; days; weeks 
need/ —> author-input; analysis; triage; maintainers-input X
Duplicate

**Comment by 0xjona** [comment]
# GITHUB-UPDATE
_A review and an update from the first week of building a GitHub project_

## _inbox;  backlog;  breakdown;  todo;  implementation;  validation;  done_

- **inbox** are the issues that do not yet have reference design docs and have not started a process of brainstorming and definition, it is also an icebox as those are issues that we are not sure we will implement, when and how.  These is the issues status as soon as they are created
- **backlog** are the issues we are discussing, which we have decided to implement but which are not yet in the todo list as they are not priority or not satisfactorily defined (it is not a todo list)
 breakdown | triage are the issues that need, before entering the todo-list, to be simplified into more specific issues (and this does not mean that they need clarification, otherwise they should be found in the backlog or inbox with a needs/clarification label);  it could also be the issues that are blocked (status stuck)
 - **todo** is the list of issues ready to be carried out, with the priority assigned, etc.
 - **implementation** means "we are writing the code” or ”we are actually producing this content"
 - **validation** means that we have entered the definitive review / validation process
 - **done** when they were closed (and then there could be a time distinction)


## _other fields_
**active |  stuck |  done** —> we can review this field as it should be a field inside the column and managed by the assignee: it means that every time the issue is moved from one column to another it undergoes a process (the breakdown process if necessary, or the implementation or validation etc), this process can be active, stuck for some reason (and here you can move back to triage to undergo a further breakdown or brainstorming process if necessary) or done (and you need done rules, i.e. that the breakdown is finished if for example a design doc has been produced).
**priority** (0 urgent, 3 non-urgent)
**due dates** (to be made explicit only when referring to external consultancy or necessary deadlines external to the milestones)
 and the **_labels_**

## About labels
- dif/ —> easy, medium, hard, expert, trivial 
outsourced; content-request; dependencies; help wanted 
- kind/ —> enhancement; discussion; support; maintenance; suggestion; BUG; test; monitor; review 
- topic/ —> documentation; infrastructure , design-front-end; design-ux; product-design; protocol-research; PM 
- effort/ —> hours; days; weeks 
- need/ —> author-input; analysis; triage; maintainers-input X
Duplicate

**Comment by 0xjona** [comment]
Is there any best practice to do this? Do we need anything like a bird eye view of the overall project with explicit dependencies?

With @irenegia we opted to implement a proper use of milestones (@nicola what do you think?)

Examples provided in the images below
![Image](https://user-images.githubusercontent.com/103100279/170213702-27165011-998a-4723-8adb-0e79c33ca0cf.png)
![Image](https://user-images.githubusercontent.com/103100279/170213703-1e231f50-5f2a-4d3a-af27-6f1ef5f7fafe.jpeg)

**Comment by irenegia** [comment]
great, leaving this in your hand @0xjona !

**Comment by nicola** [comment]
cc @daviddias might have good pointers for you or point you to people that have strong opinions on this.

**Comment by 0xjona** [comment]
I'm closing this issue since the board is more usable via EPICs and milestones!
Still improvements will be made during next months
