### ISSUE TITLE
onchain.storage pivot

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#81]
This pivoting will happen in few steps, parallel to other stages of development of the product, during #71 

**GOAL --> DEADLINE**
With this effort we want to 
- [ ] change domain name (A record pointing to 85.25.217.216 @nicola)
- [x] light front-end updates (basically substituting _retrieval pinning_ with _onchain.storage_ when needed) @Steve-Rog 
- [x] update the pitch deck that will talk about _onchain storage_ as the first UX for _retrieval pinning_ @claudiofabbro 
- [x] new repos on github to better manage code @turinglabsorg 
- [ ] discussing the oracle https://github.com/protocol/onchain-oracle

by the end of September

STEP 2 --> https://github.com/protocol/onchain-storage/issues/1
- [x] redesign of the dapp to have a more generic interface for deals
- [ ] new website (from figma draft to implementation)

STEP 3 (draft)
- [ ] twitter page? slack channels?

**Comment by turinglabsorg** [comment]
@0xjona can we close this issue since is not part of this project anymore?

**Comment by turinglabsorg** [comment]
As discussed with @irenegia and @lucaniz we're closing as not planned in this team.
