### ISSUE TITLE
first contact early storage providers and referees

### ISSUE THREAD

**Issue by 0xjona** [protocol/retriev#82]
_finding partners for retrieval pinning_

**GOAL --> DEADLINE**
With this effort we want to 
- start talking with as many storage providers and potential referees as possible
- onboard at least x  providers (@turinglabsorg what is a good number to have a stable network?)
- onboard 5 referees' nodes
by the end of September

 **storage providers and referees program**:
  Referee --> find 5 "trusted" partners in the PL network (see drand network)
  providers --> reach out, the more the better
   -  Action items:  
       - [x]  (0) #69   (remember to quote the new domain, and feature reputation score)
       - [ ] (1) recording new demo (pitch for providers, motivate them to join) **[eow]**
       - [x]  (2) @luca and @irenegia write down the list of calls to do with Jona (goal: find partners)
       - [ ] (3) drafting interest form (see the FVM one) ??
       - [ ] https://github.com/protocol/retriev/issues/15
   -  Next steps: form divulgation, user onboarding

**Comment by 0xjona** [comment]
@irenegia should we collect in a youtube channel/playlist all the presentations done so far?

**Comment by irenegia** [comment]
I think it is not necessary, we can just link the most updated one to our messages and posts

**Comment by irenegia** [comment]
Kick-off doc:
https://docs.google.com/document/d/18EFLsDEkk4MUgsHmD3V6KnSuah-FODWAo6ko2LfDJ78/edit?usp=sharing

**Comment by 0xjona** [comment]
Here's the updated [pitch desk](https://drive.google.com/file/d/1bgPb-e0cgU7T8QAlpUcaUCBJVySSBB4F/view?usp=sharing) @nicola @irenegia

**Comment by 0xjona** [comment]
###→ Partners for retrieval pinning

**For retrieval pinning we have**
- webpage (to be updated about visuals and copy)
- working demo (probably to keep the retrieval pinning name and forget about the “choose protocol/choose referees network” and also staying on testnet - after the merge I think rinkeby will not be up to date)
- pitch deck (+ video demos)
- potential candidates for partners (aka list of contacts)

**We have to**
find domain name
create onboarding program (set goals)

_the onboarding program has 2 goals_
- find partners for the bigger vision of onchain.storage starting from retrieval pinning protocol (this means we should reference onchain.storage as much as possible - reference bigger context e.g. “referees becoming oracles”)
- test the product (retrieval) with early service providers, which will join our network after testing

_The onboarding program will consist of (apart from what we already have)_
- a single slide (useful for twitter and slack channels) that sums up infos (what we need, what we give, why ecc + links to proper channels and websites)
- a funnel (can be a form, could be a page in the website..) to find an agreement with partners (how many “nodes” can you offer? for how long? starting from when?)
- a guide (readme on github + issues, or somewhere we can receive updates) both to install and to set and track metrics so that we can evaluate the tests and efforts [reports]

**Comment by turinglabsorg** [comment]
As discussed with @irenegia and @lucaniz we're closing as not planned in this team.
